### ISSUE TITLE
As a user, I could be able to share a post on social media about events I am participating in so that I can raise awareness about sustainable activities happening in the community 

### ISSUE THREAD

**Issue by EthanGordon** [dgoodare/AgileEngineering#76]

**Comment by dgoodare** [comment]
### Definition of Done
- [ ] Option to share on Twitter
- [ ] Option to share on Facebook
- [ ] Option to share on Instagram

**Comment by cameron14** [comment]
Instagram doesn't have a share button so will just leave that one out.
